In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt  
import seaborn as sns
from sklearn import datasets

In [2]:
data = pd.read_csv("train.csv")
data.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [3]:
data.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [4]:
data.shape

(1460, 81)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [6]:
# selection de variables
features = ['GrLivArea', 'BedroomAbvGr', 'FullBath']
X = data[features]
y = data['SalePrice']
X
y

0       208500
1       181500
2       223500
3       140000
4       250000
         ...
1455    175000
1456    210000
1457    266500
1458    142125
1459    147500
Name: SalePrice, Length: 1460, dtype: int64

In [7]:
# normalisation
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[0.25923135, 0.375     , 0.66666667],
       [0.17483044, 0.375     , 0.66666667],
       [0.27354936, 0.375     , 0.66666667],
       ...,
       [0.37792012, 0.5       , 0.66666667],
       [0.14016579, 0.25      , 0.33333333],
       [0.17370008, 0.375     , 0.33333333]], shape=(1460, 3))

In [8]:
y=y.values.reshape(-1,1)
y=scaler.fit_transform(y)
y

array([[0.24107763],
       [0.20358284],
       [0.26190807],
       ...,
       [0.321622  ],
       [0.14890293],
       [0.15636717]], shape=(1460, 1))

In [9]:
# donnees d entrainement et de test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [10]:
# construire l architecture du reseau
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
model = Sequential(
    [
    Dense(64, activation='relu', input_shape=(3,)),
    Dense(32, activation='relu'),
    Dense(1)
    ]
)

c:\Users\user\Documents\VENV\Python_Bases\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [11]:
model.compile(
    optimizer='adam',
    loss='mean_squared_error',
    metrics=['mean_absolute_error'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,369 (9.25 KB)

 Trainable params: 2,369 (9.25 KB)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.fit(X_train, y_train, epochs=100, validation_split=0.2)

Epoch 1/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - loss: 0.0329 - mean_absolute_error: 0.1316 - val_loss: 0.0091 - val_mean_absolute_error: 0.0791
Epoch 2/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0087 - mean_absolute_error: 0.0654 - val_loss: 0.0064 - val_mean_absolute_error: 0.0550
Epoch 3/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0073 - mean_absolute_error: 0.0584 - val_loss: 0.0049 - val_mean_absolute_error: 0.0504
Epoch 4/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0060 - mean_absolute_error: 0.0524 - val_loss: 0.0040 - val_mean_absolute_error: 0.0466
Epoch 5/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0056 - mean_absolute_error: 0.0510 - val_loss: 0.0038 - val_mean_absolute_error: 0.0460
Epoch 6/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0055 - mean_absolute_error: 0.0510 - val_loss: 0.0035 - val_mean_absolute_error: 0.0446
Epoch 7/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0053 - mean_absolute_error: 0.0498 - val_loss: 0.0034 - val_mean_absolute_error: 0.0442
Epoch 8/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: 0.0053 - mean_absolute_error: 0.0499 - val_loss: 0.0035 - val_mean_absolute_error: 0.0446
Epoch 9/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0052 - mean_absolute_error: 0.0494 - val_loss: 0.0036 - val_mean_absolute_error: 0.0456
Epoch 10/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0052 - mean_absolute_error: 0.0492 - val_loss: 0.0031 - val_mean_absolute_error: 0.0420
Epoch 11/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0051 - mean_absolute_error: 0.0489 - val_loss: 0.0031 - val_mean_absolute_error: 0.0418
Epoch 12/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0050 - mean_absolute_error: 0.0483 - val_loss: 0.0030 - val_mean_absolute_error: 0.0417
Epoch 13/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0050 - mean_absolute_error: 0.0480 - val_loss: 0.0030 - val_mean_absolute_error: 0.0411
Epoch 14/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: 0.0051 - mean_absolute_error: 0.0481 - val_loss: 0.0030 - val_mean_absolute_error: 0.0416
Epoch 15/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0050 - mean_absolute_error: 0.0484 - val_loss: 0.0030 - val_mean_absolute_error: 0.0409
Epoch 16/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0050 - mean_absolute_error: 0.0485 - val_loss: 0.0029 - val_mean_absolute_error: 0.0406
Epoch 17/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0051 - mean_absolute_error: 0.0483 - val_loss: 0.0032 - val_mean_absolute_error: 0.0431
Epoch 18/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0050 - mean_absolute_error: 0.0478 - val_loss: 0.0029 - val_mean_absolute_error: 0.0405
Epoch 19/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0049 - mean_absolute_error: 0.0481 - val_loss: 0.0033 - val_mean_absolute_error: 0.0442
Epoch 20/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0050 - mean_absolute_error: 0.0481 - val_loss: 0.0029 - val_mean_absolute_error: 0.0402
Epoch 21/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0049 - mean_absolute_error: 0.0480 - val_loss: 0.0030 - val_mean_absolute_error: 0.0421
Epoch 22/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0049 - mean_absolute_error: 0.0479 - val_loss: 0.0028 - val_mean_absolute_error: 0.0398
Epoch 23/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0049 - mean_absolute_error: 0.0480 - val_loss: 0.0028 - val_mean_absolute_error: 0.0401
Epoch 24/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0048 - mean_absolute_error: 0.0473 - val_loss: 0.0028 - val_mean_absolute_error: 0.0401
Epoch 25/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0048 - mean_absolute_error: 0.0471 - val_loss: 0.0028 - val_mean_absolute_error: 0.0401
Epoch 26/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0048 - mean_absolute_error: 0.0470 - val_loss: 0.0028 - val_mean_absolute_error: 0.0394
Epoch 27/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0048 - mean_absolute_error: 0.0471 - val_loss: 0.0028 - val_mean_absolute_error: 0.0397
Epoch 28/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0048 - mean_absolute_error: 0.0473 - val_loss: 0.0029 - val_mean_absolute_error: 0.0393
Epoch 29/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0047 - mean_absolute_error: 0.0469 - val_loss: 0.0028 - val_mean_absolute_error: 0.0392
Epoch 30/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0048 - mean_absolute_error: 0.0478 - val_loss: 0.0028 - val_mean_absolute_error: 0.0405
Epoch 31/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0048 - mean_absolute_error: 0.0475 - val_loss: 0.0027 - val_mean_absolute_error: 0.0392
Epoch 32/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0047 - mean_absolute_error: 0.0467 - val_loss: 0.0028 - val_mean_absolute_error: 0.0399
Epoch 33/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0049 - mean_absolute_error: 0.0474 - val_loss: 0.0028 - val_mean_absolute_error: 0.0389
Epoch 34/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0048 - mean_absolute_error: 0.0482 - val_loss: 0.0027 - val_mean_absolute_error: 0.0386
Epoch 35/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0049 - mean_absolute_error: 0.0486 - val_loss: 0.0028 - val_mean_absolute_error: 0.0396
Epoch 36/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0048 - mean_absolute_error: 0.0473 - val_loss: 0.0027 - val_mean_absolute_error: 0.0387
Epoch 37/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0048 - mean_absolute_error: 0.0470 - val_loss: 0.0028 - val_mean_absolute_error: 0.0401
Epoch 38/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0047 - mean_absolute_error: 0.0468 - val_loss: 0.0030 - val_mean_absolute_error: 0.0421
Epoch 39/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0047 - mean_absolute_error: 0.0471 - val_loss: 0.0028 - val_mean_absolute_error: 0.0387
Epoch 40/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0047 - mean_absolute_error: 0.0468 - val_loss: 0.0031 - val_mean_absolute_error: 0.0424
Epoch 41/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0047 - mean_absolute_error: 0.0467 - val_loss: 0.0026 - val_mean_absolute_error: 0.0380
Epoch 42/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0047 - mean_absolute_error: 0.0479 - val_loss: 0.0028 - val_mean_absolute_error: 0.0404
Epoch 43/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mean_absolute_error: 0.0465 - val_loss: 0.0026 - val_mean_absolute_error: 0.0381
Epoch 44/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0046 - mean_absolute_error: 0.0468 - val_loss: 0.0030 - val_mean_absolute_error: 0.0419
Epoch 45/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0048 - mean_absolute_error: 0.0477 - val_loss: 0.0027 - val_mean_absolute_error: 0.0377
Epoch 46/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0047 - mean_absolute_error: 0.0467 - val_loss: 0.0027 - val_mean_absolute_error: 0.0383
Epoch 47/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0047 - mean_absolute_error: 0.0477 - val_loss: 0.0027 - val_mean_absolute_error: 0.0386
Epoch 48/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0046 - mean_absolute_error: 0.0465 - val_loss: 0.0026 - val_mean_absolute_error: 0.0381
Epoch 49/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0045 - mean_absolute_error: 0.0462 - val_loss: 0.0028 - val_mean_absolute_error: 0.0400
Epoch 50/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0047 - mean_absolute_error: 0.0476 - val_loss: 0.0027 - val_mean_absolute_error: 0.0376
Epoch 51/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0046 - mean_absolute_error: 0.0466 - val_loss: 0.0026 - val_mean_absolute_error: 0.0384
Epoch 52/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0046 - mean_absolute_error: 0.0469 - val_loss: 0.0027 - val_mean_absolute_error: 0.0396
Epoch 53/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - loss: 0.0047 - mean_absolute_error: 0.0473 - val_loss: 0.0026 - val_mean_absolute_error: 0.0379
Epoch 54/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0046 - mean_absolute_error: 0.0471 - val_loss: 0.0028 - val_mean_absolute_error: 0.0399
Epoch 55/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mean_absolute_error: 0.0469 - val_loss: 0.0026 - val_mean_absolute_error: 0.0376
Epoch 56/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0045 - mean_absolute_error: 0.0465 - val_loss: 0.0028 - val_mean_absolute_error: 0.0402
Epoch 57/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0046 - mean_absolute_error: 0.0471 - val_loss: 0.0026 - val_mean_absolute_error: 0.0374
Epoch 58/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0045 - mean_absolute_error: 0.0463 - val_loss: 0.0026 - val_mean_absolute_error: 0.0374
Epoch 59/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mean_absolute_error: 0.0475 - val_loss: 0.0027 - val_mean_absolute_error: 0.0398
Epoch 60/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0046 - mean_absolute_error: 0.0473 - val_loss: 0.0026 - val_mean_absolute_error: 0.0374
Epoch 61/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0046 - mean_absolute_error: 0.0469 - val_loss: 0.0026 - val_mean_absolute_error: 0.0375
Epoch 62/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0045 - mean_absolute_error: 0.0458 - val_loss: 0.0026 - val_mean_absolute_error: 0.0375
Epoch 63/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0044 - mean_absolute_error: 0.0460 - val_loss: 0.0026 - val_mean_absolute_error: 0.0386
Epoch 64/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - loss: 0.0045 - mean_absolute_error: 0.0462 - val_loss: 0.0026 - val_mean_absolute_error: 0.0371
Epoch 65/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0047 - mean_absolute_error: 0.0469 - val_loss: 0.0025 - val_mean_absolute_error: 0.0370
Epoch 66/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0045 - mean_absolute_error: 0.0460 - val_loss: 0.0029 - val_mean_absolute_error: 0.0410
Epoch 67/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0046 - mean_absolute_error: 0.0467 - val_loss: 0.0026 - val_mean_absolute_error: 0.0372
Epoch 68/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mean_absolute_error: 0.0463 - val_loss: 0.0027 - val_mean_absolute_error: 0.0379
Epoch 69/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mean_absolute_error: 0.0470 - val_loss: 0.0026 - val_mean_absolute_error: 0.0379
Epoch 70/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0046 - mean_absolute_error: 0.0476 - val_loss: 0.0027 - val_mean_absolute_error: 0.0397
Epoch 71/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.0046 - mean_absolute_error: 0.0468 - val_loss: 0.0026 - val_mean_absolute_error: 0.0379
Epoch 72/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0044 - mean_absolute_error: 0.0462 - val_loss: 0.0033 - val_mean_absolute_error: 0.0448
Epoch 73/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0046 - mean_absolute_error: 0.0468 - val_loss: 0.0025 - val_mean_absolute_error: 0.0369
Epoch 74/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0044 - mean_absolute_error: 0.0457 - val_loss: 0.0025 - val_mean_absolute_error: 0.0373
Epoch 75/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0044 - mean_absolute_error: 0.0456 - val_loss: 0.0025 - val_mean_absolute_error: 0.0369
Epoch 76/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0045 - mean_absolute_error: 0.0468 - val_loss: 0.0029 - val_mean_absolute_error: 0.0412
Epoch 77/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0045 - mean_absolute_error: 0.0458 - val_loss: 0.0026 - val_mean_absolute_error: 0.0374
Epoch 78/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0045 - mean_absolute_error: 0.0463 - val_loss: 0.0025 - val_mean_absolute_error: 0.0368
Epoch 79/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0044 - mean_absolute_error: 0.0455 - val_loss: 0.0025 - val_mean_absolute_error: 0.0373
Epoch 80/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0044 - mean_absolute_error: 0.0463 - val_loss: 0.0027 - val_mean_absolute_error: 0.0375
Epoch 81/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0045 - mean_absolute_error: 0.0471 - val_loss: 0.0028 - val_mean_absolute_error: 0.0404
Epoch 82/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0044 - mean_absolute_error: 0.0464 - val_loss: 0.0027 - val_mean_absolute_error: 0.0377
Epoch 83/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0045 - mean_absolute_error: 0.0464 - val_loss: 0.0027 - val_mean_absolute_error: 0.0394
Epoch 84/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - loss: 0.0044 - mean_absolute_error: 0.0461 - val_loss: 0.0025 - val_mean_absolute_error: 0.0365
Epoch 85/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0043 - mean_absolute_error: 0.0459 - val_loss: 0.0027 - val_mean_absolute_error: 0.0391
Epoch 86/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0044 - mean_absolute_error: 0.0458 - val_loss: 0.0025 - val_mean_absolute_error: 0.0368
Epoch 87/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0044 - mean_absolute_error: 0.0459 - val_loss: 0.0025 - val_mean_absolute_error: 0.0366
Epoch 88/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0043 - mean_absolute_error: 0.0453 - val_loss: 0.0027 - val_mean_absolute_error: 0.0377
Epoch 89/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0046 - mean_absolute_error: 0.0475 - val_loss: 0.0025 - val_mean_absolute_error: 0.0368
Epoch 90/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0044 - mean_absolute_error: 0.0453 - val_loss: 0.0025 - val_mean_absolute_error: 0.0370
Epoch 91/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0044 - mean_absolute_error: 0.0460 - val_loss: 0.0025 - val_mean_absolute_error: 0.0367
Epoch 92/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0044 - mean_absolute_error: 0.0460 - val_loss: 0.0025 - val_mean_absolute_error: 0.0371
Epoch 93/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mean_absolute_error: 0.0454 - val_loss: 0.0026 - val_mean_absolute_error: 0.0367
Epoch 94/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 0.0044 - mean_absolute_error: 0.0455 - val_loss: 0.0025 - val_mean_absolute_error: 0.0369
Epoch 95/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0043 - mean_absolute_error: 0.0454 - val_loss: 0.0031 - val_mean_absolute_error: 0.0438
Epoch 96/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 15ms/step - loss: 0.0049 - mean_absolute_error: 0.0492 - val_loss: 0.0025 - val_mean_absolute_error: 0.0366
Epoch 97/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 16ms/step - loss: 0.0045 - mean_absolute_error: 0.0469 - val_loss: 0.0025 - val_mean_absolute_error: 0.0369
Epoch 98/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 18ms/step - loss: 0.0043 - mean_absolute_error: 0.0450 - val_loss: 0.0026 - val_mean_absolute_error: 0.0378
Epoch 99/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 1s 17ms/step - loss: 0.0043 - mean_absolute_error: 0.0454 - val_loss: 0.0026 - val_mean_absolute_error: 0.0379
Epoch 100/100
30/30 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - loss: 0.0048 - mean_absolute_error: 0.0469 - val_loss: 0.0029 - val_mean_absolute_error: 0.0391

In [14]:
# evaluation
model.evaluate(X_test, y_test)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 0.0053 - mean_absolute_error: 0.0484

[0.005251005757600069, 0.04842543974518776]

In [15]:
# calcul accuracy
test_loss, test_acc = model.evaluate(X_test, y_test)
print('Test accuracy:', test_acc)
print('Test loss',test_loss)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 0.0053 - mean_absolute_error: 0.0484
Test accuracy: 0.04842543974518776
Test loss 0.005251005757600069

In [16]:
features = ['GrLivArea', 'BedroomAbvGr', 'FullBath']
X = data[features]
y = data['SalePrice'].values.reshape(-1, 1)

scaler_x = MinMaxScaler()
scaler_y = MinMaxScaler()

X_scaled = scaler_x.fit_transform(X)
y_scaled = scaler_y.fit_transform(y)

###  DEVOIR :  meme que le precedent mais avec ce reseau de neurones

In [17]:
# ====================== FONCTION DE PRÉDICTION (Version corrigée) ======================

def predire_prix_maison(GrLivArea, BedroomAbvGr, FullBath):
    
    nouvelle_maison = np.array([[GrLivArea, BedroomAbvGr, FullBath]])
    
    # === IMPORTANT : Utilise scaler_x et scaler_y ===
    nouvelle_maison_scaled = scaler_x.transform(nouvelle_maison)   # scaler pour X
    
    prediction_scaled = model.predict(nouvelle_maison_scaled, verbose=0)
    
    prix_reel = scaler_y.inverse_transform(prediction_scaled)     # scaler pour y
    
    return round(float(prix_reel[0][0]), 2)


# ====================== TESTS ======================
print("Test 1 :", predire_prix_maison(2000, 3, 2), "$")
print("Test 2 :", predire_prix_maison(1500, 2, 1), "$")
print("Test 3 :", predire_prix_maison(2500, 4, 3), "$")

c:\Users\user\Documents\VENV\Python_Bases\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

Test 1 : 272597.0 $
Test 2 : 182265.86 $

c:\Users\user\Documents\VENV\Python_Bases\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(
c:\Users\user\Documents\VENV\Python_Bases\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but MinMaxScaler was fitted with feature names
  warnings.warn(

Test 3 : 349340.56 $

In [19]:
import joblib

# Sauvegarder le modèle Keras
model.save("rf_model.keras")  # ou "rf_model.h5"

# Sauvegarder les scalers
joblib.dump(scaler_x, "scaler_x.joblib")
joblib.dump(scaler_y, "scaler_y.joblib")

print("✅ Modèle et scalers sauvegardés avec succès !")

✅ Modèle et scalers sauvegardés avec succès !